# Generated by Django 4.2.4 on 2023-08-14 15:35

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_permission_and_group(apps, schema_editor):

    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'user'))


    permission = Permission.objects.create(
        codename='can_view_bookings',
        name='Can view bookings',
        content_type=content_type,
    )

    group, created = Group.objects.get_or_create(name='Cinema Owner')

    group.permissions.add(permission)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permission_and_group),
    ]
