default_language_version:
  python: python3.10

repos:

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --rcfile=.pylintrc
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^.*\/migrations\/.*\.py$
        language: python
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
        exclude: ^.*\/migrations\/.*\.py$
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the version you prefer
    hooks:
      - id: isort
        exclude: ^.*\/migrations\/.*\.py$
        language: python
        language_version: python3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5  # Use the version you prefer
    hooks:
      - id: bandit
        exclude: ^(.*\/migrations\/.*\.py$)|(.*\/tests\/.*\.py$)
        language: python
        language_version: python3
