version: '3'

services:
  web:
    build: .
    command: bash -c "sleep 3 && gunicorn capitol_cinema.wsgi:application -b 0.0.0.0:8000 -w 3"
    # command: bash -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - migrations

  migrations:
    build: .
    image: enterprise
     # ; python manage.py collectstatic --noinput
    command: bash -c "python manage.py check; python manage.py migrate --noinput"
    volumes:
      - .:/code
    depends_on:
      - db
    
  db:
    image: postgres:15.4-alpine
    volumes:
      - .:/tmp/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb


  testdb:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    ports:
      - 5433:5432