version: '3'

services:

  nginx:
    image: nginx:latest
    #cp -fr /code/staticfiles/* /usr/share/nginx/html/static/
    command: bash -c "sleep 10 && echo hola && nginx -g 'daemon off;'"
    volumes:
      - .:/code
      - ./staticfiles:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - db
      - collectstatic


  web:
    build: .
    command: bash -c "sleep 3 && gunicorn capitol_cinema.wsgi:application -b 0.0.0.0:8000 -w 3"
    # command: bash -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - static_volume:/staticfiles
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - migrations

  collectstatic:
    build: .
    image: collect
    command: bash -c "python manage.py collectstatic --noinput"
    volumes:
      - static_volume:/staticfiles
      - .:/code
    depends_on:
      - db
  

  migrations:
    build: .
    image: resources_web
     # ; python manage.py collectstatic --noinput
    command: bash -c "python manage.py check; python manage.py migrate --noinput"
    volumes:
      - .:/code
    depends_on:
      - db
    
  db:
    image: postgres:15.4-alpine
    volumes:
      - .:/tmp/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb


  testdb:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    ports:
      - 5433:5432


volumes:
  static_volume: