# Generated by Django 4.2.4 on 2023-08-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('cinemas', '0001_initial'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screnning',
            new_name='Screening',
        ),
    ]
