# Generated by Django 4.2.4 on 2023-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_rename_screnning_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
