name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
      - 'devel'

jobs:

  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pre-commit
      uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag myimage

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag myimage
    - name: Run tests inside Docker container
      run: docker run myimage pytest 

  coverage:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Django Coverage action
      uses: actions/python-django-coverage-gitHub-action@0.9
      with:
        django-app: 'sample_app'
        minimum-coverage: '86'