name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
      - 'devel'

jobs:

  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.12
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && pylint --load-plugins pylint_django --django-settings-module=capitol_cinema.settings **/*.py

  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pre-commit
      uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag myimage

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag myimage
    - name: Run tests inside Docker container
      run: docker run myimage pytest 